# Generated by Django 6.0.2 on 2026-03-02 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=12, unique=True)),
                ('nombre_apellido', models.CharField(max_length=120)),
                ('concesionario', models.CharField(blank=True, default='', max_length=120)),
                ('credencial', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['dni'],
            },
        ),
        migrations.CreateModel(
            name='VoucherTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('INVITADO', 'Invitado')], max_length=20, unique=True)),
                ('cupo_por_dia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cupo_por_dia__gte', 1)), name='ck_voucher_tipo_cupo_por_dia_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('totem_id', models.CharField(max_length=50)),
                ('ticket_numero', models.CharField(max_length=64, unique=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.persona')),
                ('voucher_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.vouchertipo')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['dia', 'voucher_tipo'], name='idx_ticket_dia_voucher'), models.Index(fields=['totem_id', 'creado_en'], name='idx_ticket_totem_fecha')],
            },
        ),
        migrations.CreateModel(
            name='CupoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('usados', models.PositiveSmallIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='core.persona')),
                ('voucher_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupos', to='core.vouchertipo')),
            ],
            options={
                'ordering': ['-dia', 'persona_id', 'voucher_tipo_id'],
                'indexes': [models.Index(fields=['dia', 'voucher_tipo'], name='idx_cupo_dia_voucher')],
                'constraints': [models.UniqueConstraint(fields=('persona', 'voucher_tipo', 'dia'), name='uq_cupo_por_dia'), models.CheckConstraint(condition=models.Q(('usados__gte', 0)), name='ck_cupo_diario_usados_gte_0')],
            },
        ),
    ]
