# Generated by Django 6.0.2 on 2026-03-03 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertipo',
            name='codigo',
            field=models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('INVITADO', 'Invitado'), ('INVITADO_DESAYUNO', 'Invitado desayuno'), ('INVITADO_ALMUERZO', 'Invitado almuerzo')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PoolDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('DESAYUNO', 'Pool fijos desayuno'), ('ALMUERZO', 'Pool fijos almuerzo'), ('INVITADO_DESAYUNO', 'Pool invitados desayuno'), ('INVITADO_ALMUERZO', 'Pool invitados almuerzo')], max_length=24)),
                ('dia', models.DateField()),
                ('stock_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('usados', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dia', 'codigo'],
                'indexes': [models.Index(fields=['dia', 'codigo'], name='idx_pool_diario_dia_codigo')],
                'constraints': [models.UniqueConstraint(fields=('dia', 'codigo'), name='uq_pool_diario_dia_codigo'), models.CheckConstraint(condition=models.Q(('stock_total__gte', 1)), name='ck_pool_diario_stock_gte_1'), models.CheckConstraint(condition=models.Q(('usados__gte', 0)), name='ck_pool_diario_usados_gte_0')],
            },
        ),
    ]
