# Generated by Django 6.0.2 on 2026-03-03 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vouchertipo_codigo_pooldiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanjeOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('totem_id', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_canje', to='core.persona')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.canjeoperacion'),
        ),
        migrations.CreateModel(
            name='CanjeOperacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida_codigo', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo')], max_length=20)),
                ('canjear_propio', models.BooleanField(default=False)),
                ('cantidad_invitados', models.PositiveSmallIntegerField(default=0)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.canjeoperacion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='canjeoperacion',
            index=models.Index(fields=['dia', 'totem_id'], name='idx_canje_dia_totem'),
        ),
        migrations.AddIndex(
            model_name='canjeoperacion',
            index=models.Index(fields=['persona', 'creado_en'], name='idx_canje_persona_fecha'),
        ),
        migrations.AddIndex(
            model_name='canjeoperacionitem',
            index=models.Index(fields=['comida_codigo'], name='idx_canje_item_comida'),
        ),
        migrations.AddConstraint(
            model_name='canjeoperacionitem',
            constraint=models.UniqueConstraint(fields=('operacion', 'comida_codigo'), name='uq_canje_item_operacion_comida'),
        ),
        migrations.AddConstraint(
            model_name='canjeoperacionitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_invitados__gte', 0)), name='ck_canje_item_invitados_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='canjeoperacionitem',
            constraint=models.CheckConstraint(condition=models.Q(('canjear_propio', True), ('cantidad_invitados__gte', 1), _connector='OR'), name='ck_canje_item_propio_o_invitado'),
        ),
    ]
