# Generated by Django 6.0.2 on 2026-03-04 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _normalize_empresa_code(raw: str) -> str:
    cleaned = "".join(
        ch for ch in str(raw or "").strip().upper() if ch.isalnum() or ch in {"_", "-"}
    )
    return cleaned[:30] or "DEFAULT"


def forwards_assign_default_empresa(apps, schema_editor):
    Empresa = apps.get_model("core", "Empresa")
    Totem = apps.get_model("core", "Totem")
    Persona = apps.get_model("core", "Persona")
    PoolDiario = apps.get_model("core", "PoolDiario")
    Ticket = apps.get_model("core", "Ticket")
    CanjeOperacion = apps.get_model("core", "CanjeOperacion")

    default_code = _normalize_empresa_code(getattr(settings, "DEFAULT_EMPRESA_CODE", "DEFAULT"))
    empresa, _ = Empresa.objects.get_or_create(
        codigo=default_code,
        defaults={"nombre": default_code, "activo": True},
    )
    if not empresa.activo:
        empresa.activo = True
        empresa.save(update_fields=["activo", "actualizado_en"])

    Persona.objects.filter(empresa__isnull=True).update(empresa_id=empresa.id)
    PoolDiario.objects.filter(empresa__isnull=True).update(empresa_id=empresa.id)

    totem_codes = set()
    for totem_id in Ticket.objects.values_list("totem_id", flat=True).iterator():
        normalized = str(totem_id or "").strip()
        if normalized:
            totem_codes.add(normalized)
    for totem_id in CanjeOperacion.objects.values_list("totem_id", flat=True).iterator():
        normalized = str(totem_id or "").strip()
        if normalized:
            totem_codes.add(normalized)

    for totem_code in sorted(totem_codes):
        Totem.objects.get_or_create(
            codigo=totem_code,
            defaults={
                "nombre": totem_code,
                "empresa_id": empresa.id,
                "activo": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_canjeoperacion_ticket_operacion_canjeoperacionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["codigo"]},
        ),
        migrations.CreateModel(
            name="Totem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=50, unique=True)),
                ("nombre", models.CharField(blank=True, default="", max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="totems",
                        to="core.empresa",
                    ),
                ),
            ],
            options={"ordering": ["codigo"]},
        ),
        migrations.AddField(
            model_name="persona",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personas",
                to="core.empresa",
            ),
        ),
        migrations.AddField(
            model_name="pooldiario",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pools_diarios",
                to="core.empresa",
            ),
        ),
        migrations.RunPython(forwards_assign_default_empresa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="persona",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personas",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="pooldiario",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pools_diarios",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dni",
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterModelOptions(
            name="persona",
            options={"ordering": ["empresa_id", "dni"]},
        ),
        migrations.AlterModelOptions(
            name="pooldiario",
            options={"ordering": ["-dia", "empresa_id", "codigo"]},
        ),
        migrations.RemoveConstraint(
            model_name="pooldiario",
            name="uq_pool_diario_dia_codigo",
        ),
        migrations.RemoveIndex(
            model_name="pooldiario",
            name="idx_pool_diario_dia_codigo",
        ),
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.UniqueConstraint(
                fields=("empresa", "dni"),
                name="uq_persona_empresa_dni",
            ),
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(fields=["empresa", "dni"], name="idx_persona_empresa_dni"),
        ),
        migrations.AddConstraint(
            model_name="pooldiario",
            constraint=models.UniqueConstraint(
                fields=("empresa", "dia", "codigo"),
                name="uq_pool_diario_empresa_dia_codigo",
            ),
        ),
        migrations.AddIndex(
            model_name="pooldiario",
            index=models.Index(
                fields=["empresa", "dia", "codigo"],
                name="idx_pool_diario_emp_dia_codigo",
            ),
        ),
    ]
