# Generated by Django 6.0.2 on 2026-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_multiempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='puede_invitar',
            field=models.BooleanField(default=False),
        ),
    ]
