# Generated by Django 6.0.2 on 2026-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_persona_puede_invitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_vianda',
            field=models.CharField(choices=[('CLASICO', 'Clasico'), ('VEGETARIANO', 'Vegetariano')], default='CLASICO', max_length=12),
        ),
    ]
