# Generated by Django 6.0.2 on 2026-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_persona_tipo_vianda_celiaco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pooldiario',
            options={'ordering': ['-dia', 'empresa_id', 'scope_codigo', 'codigo']},
        ),
        migrations.RemoveConstraint(
            model_name='pooldiario',
            name='uq_pool_diario_empresa_dia_codigo',
        ),
        migrations.RemoveIndex(
            model_name='pooldiario',
            name='idx_pool_diario_emp_dia_codigo',
        ),
        migrations.AddField(
            model_name='pooldiario',
            name='scope_codigo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='pooldiario',
            index=models.Index(fields=['empresa', 'scope_codigo', 'dia', 'codigo'], name='idx_pool_emp_scope_dia_cod'),
        ),
        migrations.AddConstraint(
            model_name='pooldiario',
            constraint=models.UniqueConstraint(fields=('empresa', 'scope_codigo', 'dia', 'codigo'), name='uq_pool_emp_scope_dia_cod'),
        ),
    ]
