# Generated by Django 6.0.2 on 2026-03-09 18:54

from django.db import migrations, models


def seed_merienda_vouchers(apps, schema_editor):
    VoucherTipo = apps.get_model("core", "VoucherTipo")
    for codigo, cupo in (
        ("MERIENDA", 1),
        ("INVITADO_MERIENDA", 5),
    ):
        VoucherTipo.objects.update_or_create(
            codigo=codigo,
            defaults={"cupo_por_dia": cupo},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pooldiario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjeoperacionitem',
            name='comida_codigo',
            field=models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pooldiario',
            name='codigo',
            field=models.CharField(choices=[('DESAYUNO', 'Pool fijos desayuno'), ('ALMUERZO', 'Pool fijos almuerzo'), ('MERIENDA', 'Pool fijos merienda'), ('INVITADO_DESAYUNO', 'Pool invitados desayuno'), ('INVITADO_ALMUERZO', 'Pool invitados almuerzo'), ('INVITADO_MERIENDA', 'Pool invitados merienda')], max_length=24),
        ),
        migrations.AlterField(
            model_name='vouchertipo',
            name='codigo',
            field=models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('INVITADO', 'Invitado'), ('INVITADO_DESAYUNO', 'Invitado desayuno'), ('INVITADO_ALMUERZO', 'Invitado almuerzo'), ('INVITADO_MERIENDA', 'Invitado merienda')], max_length=20, unique=True),
        ),
        migrations.RunPython(seed_merienda_vouchers, migrations.RunPython.noop),
    ]
